### ISSUE TITLE
Getting additional update of state value 

### ISSUE THREAD

**Issue by JoeGaffney** [justinmahar/react-storage-complete#2]
Hey, I'm getting an additional update of the state value when it is a complex object type. Which is triggering a useEffect twice.

Data looks identical, which probably means it is being set twice somehow?

`  // causes an additonal update
  const [filterData, setFilterData] = useLocalStorage<any>(
    "filterData",
    getFilterDefaults(props.identifier, props.defaultCols, props.parameters),
    { prefix: props.identifier }
  );

  // no additonal update
  // const [filterData, setFilterData] = useState(
  //   getFilterDefaults(props.identifier, props.defaultCols, props.parameters)
  // );`

Great package by the way very convenient and has reduced allot of complexity in my code.
![Capture](https://user-images.githubusercontent.com/11944251/233095948-3205d0fe-8fd3-4512-9b83-52b48b81acad.PNG)
![Capture](https://user-images.githubusercontent.com/11944251/233096157-996a60f6-bd43-4b4c-9146-186fac6304a0.PNG)

**Comment by JoeGaffney** [comment]
![image](https://user-images.githubusercontent.com/11944251/233112678-e325e182-f5a2-45c1-bf0e-c747f21130b0.png)

I think it's to do with it being an object that I am storing. Possibly in this case needs to be converted to a string to check for a type of equality before setting again. As react always treats state values that are objects as being unique.

Something like this maybe?

`           let decodedValue = getDecodedValue()
            console.log(decodedValue)

            if (JSON.stringify(state) !== JSON.stringify(decodedValue))
            {
                setState(getDecodedValue());
            }
`

**Comment by JoeGaffney** [comment]
Hey @justinmahar I made a branch with an idea of how to do this but I don't think I have permissions to push?

**Comment by justinmahar** [comment]
Hey @JoeGaffney! I think your hunch is correct. This probably has to do with the emitter that notifies other hooks to keep them in sync. I bet if you pass `emitterDisabled` as `true` you won't see the issue anymore. This is because, as you said, react sees each object as unique.

**Comment by justinmahar** [comment]
@JoeGaffney I've published a possible fix for this. Now, hooks will not sync with themselves on change, they'll only update when other hooks of the same localhost key change. I believe this will solve the issue you're seeing.

To get the fix:

```bash
npm i react-storage-complete@latest
```

Let me know how it goes!

**Comment by JoeGaffney** [comment]
Hey, thanks just testing now.

**Comment by JoeGaffney** [comment]
Hey, I just tested with your latest and still getting it set twice. 

I can push my branch if you give me permissions to basically I am just doing this to stop it setting if there is a match.

```ts
// Wrapping setState so we can do an equality check on object types to avoid setting again
  const setStateWrapper = (value: any): void => {
    if (typeof value === 'object')
    {
      if (JSON.stringify(state) !== JSON.stringify(value))
      {
        setState(value);
      }
    }
    else
    {
      setState(value);
    }
  };

  // If the scope, key, storage, or options, change, decode and set the value, and set it as initialized.
  React.useEffect(() => {
    if (opts.shouldInitialize) {
      setStateWrapper(getDecodedValue());
      setInitialized(true);
    } else {
      // When there's no scope, set as not initialized
      setState(defaultValue);
      setInitialized(false);
    }
  }, [getDecodedValue, opts.shouldInitialize, defaultValue, scopedStorageKey]);
```

**Comment by justinmahar** [comment]
Ahh I see what you're saying

**Comment by justinmahar** [comment]
Alright, I've added a check to confirm the values are different when calling the setter. The check uses the encoder provided in options, or the default JSON.stringify() one. That way it'll honor the user's encoding preferences if specified

Let's try this again-- give it an update and see if your issue is resolved:

```
npm i react-storage-complete@latest
```

**Comment by justinmahar** [comment]
@JoeGaffney Just added an additional check around setState during init to eliminate any rogue extra calls. All cases should be covered around setState to check for equality now

```bash
npm i react-storage-complete@latest
```

All good on your end?

**Comment by JoeGaffney** [comment]
Hey, I no longer get the double setting, but I think there has been some degradation as I also cannot update the state in the same way afterwards.

**Comment by justinmahar** [comment]
How so? Any more info you can provide? I'm playing around w/ object setting via the demo and it's working there at least. What use case is it not letting you update the state in?

**Comment by justinmahar** [comment]
Found another little bug where clearing state (setting to `undefined`) wouldn't fall back on the default value when it was specified, and pushed that update to npm, fyi 👍

**Comment by JoeGaffney** [comment]
Hey, sorry I haven't had time to test the latest or give a clear example. 

I'm pretty sure it was happening when I was passing the useLocalStorage set function down to another component and setting it from there it was not changing.

I'm currently just running an earlier version with an equality check patched in.

**Comment by justinmahar** [comment]
Closing for now.
